pipeline {
    agent any
    stages {
        stage('Check PR Status') {
            steps {

            }
        }
        stage('Build') {
            steps {

            }
        }

        stage('Test') {
            steps {

            }
        }

        stage('Merge') {
            steps {

            }
        }
    }
}